### ISSUE TITLE
TODOMVC bugs

### ISSUE THREAD

**Issue by Fresheyeball** [anp/moxie#124]
- [ ] Local store not implemented
- [ ] "whoaaa" present on first load
- [ ] Green check and no strike is an invalid state
- [ ] Toggleing around filters changes check mark state of elements
- [ ] Remaining item count is inconsistent with state
- [ ] Toggling to "active" removes strike on some elements
- [ ] Toggle all doesn't impact check mark state
- [ ] No check mark with strike is an invalid state

**Comment by anp** [comment]
Thank you for reporting all these!

There are still some bugs I'm finding as I get the [e2e tests] working, but I think I've addressed all of your findings except local storage.

[e2e tests]: https://github.com/anp/moxie/tree/main/dom/examples/todo/e2e
