### ISSUE TITLE
ButtonBuilder docs doesn't show properly

### ISSUE THREAD

**Issue by MuhannadAlrusayni** [anp/moxie#129]
looks like there is a bug in `moxie_dom::elements::froms::ButtonBuilder` docs,  the page doesn't seems to include all the docs properly.

https://moxie.rs/target/doc/moxie_dom/elements/forms/struct.ButtonBuilder.html

Here is what it looks like in my screen:

![لقطة شاشة من 2020-06-11 17-14-11](https://user-images.githubusercontent.com/14802524/84396428-02cd9f00-ac07-11ea-8419-3e7f2d443241.png)

**Comment by MuhannadAlrusayni** [comment]
Another thing I notes is the search input is not usable, when I click on it nothing happen (e.g. no focus happen).

I opened the DevTools and find an error that doesn't show up in other docs pages:

![لقطة شاشة من 2020-06-11 17-21-17](https://user-images.githubusercontent.com/14802524/84397958-fe55b600-ac07-11ea-91e8-723904efb0b2.png)

**Comment by anp** [comment]
Thank you for the report! I've taken a look a couple of times and gotten stumped, but just figured it out. There's a bunch of unescaped HTML in the doc comments that I adapted from MDN content, and rustdoc treats them as markdown which is allowed to have HTML literals. Should have a fix for this shortly.
