### ISSUE TITLE
`topo::Point`should be `pub` (or other solution)

### ISSUE THREAD

**Issue by rebo** [anp/moxie#143]
Topo correctly maps the topology of nested functions which often correspond to nodes in a UI tree.

However sometimes one wishes to represent UI trees not directly nested within the main topology. Therefore one needs a mechanism to "re-root" the topology for an isolated structure.

This can currently be achieved with: 

```rust
illicit::Env::hide::<topo::Point>();

topo::call(||{
    
    ...
    
})
```

However in the latest master `Point` is no longer pub therefore this is not possible.

So a quick fix is make Point pub again.

A longer fix might be to generate an api for this kind of re-rooting.

Personally I favour the quick fix of making `Point` `pub`  because this is a bit of an edge case and as such getting hands dirty with manually invoking  `illicit::env::hide` is probably fine.

edit: Just a note , to be certain of rerooting It looks like I am having to currently use this pattern. Would be great if there was a more efficient way.

```rust
topo::call(||{
    illicit::Env::hide::<topo::Point>();
    topo::call(||{

         ...


    })    
})
```

**Comment by anp** [comment]
I agree this is a use case that needs to be covered, but I actually prefer adding an explicit re-rooting API for a couple of reasons:

* moxie had it once upon a time already
* a free function like `root()` exposes a "smaller contract" than making `Point` public again, i.e. we don't have to reason about future changes to `Point` in light of its visibility
* I'm not sure how best to document/teach the re-rooting functionality except with its own type in the rustdoc

I opened https://github.com/anp/moxie/pull/145 for your review so I can make sure this addresses your needs!
