### ISSUE TITLE
Bassic starter implementation is missing

### ISSUE THREAD

**Issue by WHK102** [anp/moxie#262]
Any official hello world to implement moxie in rust?

**Comment by anp** [comment]
Hi! Right now the web is the only supported target and we have a few examples in the repo: https://github.com/anp/moxie/tree/main/dom/examples. I think that covers what you're looking for, but please re-open the issue if there's something else!

**Comment by anp** [comment]
I'll also note that we need a real getting started guide, planning to write that before moxie-dom goes to crates.io.
