### ISSUE TITLE
Moxie's website leads to 404.

### ISSUE THREAD

**Issue by XAMPPRocky** [anp/moxie#33]

**Comment by XAMPPRocky** [comment]
I see the HTML, it's not loading the CSS or JS.

**Comment by anp** [comment]
There isn’t any CSS or JS yet. Sounds like that’s working, still need to get the examples and docs from master uploading.

**Comment by anp** [comment]
The examples are live and so are the docs, as far as I can tell. It was only a minor slog through CI. Thanks!

**Comment by XAMPPRocky** [comment]
There are JS scripts and JS & CSS source maps that are trying to be loaded.
![Screenshot 2019-08-29 at 10 02 24](https://user-images.githubusercontent.com/4464295/63922018-26db3d80-ca44-11e9-9325-757fb7d6afe8.png)

**Comment by anp** [comment]
`reloadOnChanges.js` won't load because that's for local development. Good catch on the sourcemaps.
