### ISSUE TITLE
Second 'on' handler ignored

### ISSUE THREAD

**Issue by Schmavery** [anp/moxie#48]
Tried to update two state variables on the same button press:

```
let total = state!(|| 10);
let current = state!(|| 10);
element!("button", |e| e
  .attr("type", "button")
  .on(|_: ClickEvent, _| Some(0), current)
  .on(|_: ClickEvent, _| Some(0), total)
  .inner(|| text!("Reset")));
```

Seems like only the first one is getting updated (I even swapped the order and tried again to double check haha).

**Comment by anp** [comment]
Yep!

I think we need to include the `topo::Id` of the state key in a tuple with the event name and perhaps the TypeId of the callback [here](https://github.com/anp/moxie/blob/master/dom/src/lib.rs#L112).
