### ISSUE TITLE
Document topo::Id's thread-local behavior

### ISSUE THREAD

**Issue by rebo** [anp/moxie#66]
Further to discussions on Discord.  With caller tracking being possibly implemented in rustc it is important to understand what this means for spawned threads and parallelism in general.

In the below by  execution context I mean the environment associated with the callsite generated by either topos::root! , topos::call! or [topos::nested]. This includes the topos::current() Id.

Questions include:

1) What, if any, should the default behaviour be for the execution context in a spawned thread? 

For instance thread with Id:4 spawns a thread, should that new thread have any particularly Id.

2) What guarantees, if any, should there be regarding subsequent calls to callsite tracking methods in a new thread.

For instance thread with Id:4 spawns a thread, if it has also by default has Id:4 can there be any guarantee that the id of the first new callsite in that thread would be invariant over consecutive thread spawns. 

3) Should there be explicit control over the above behaviour and execution context via some kind of spawn threading api.

4) if a thread is spawned and then executes a loop which in turn executes several call-site tracked methods (with a revisit to each call-site intended). How does one ensure that this happens. Would a topo::root! be sufficient to guarantee this.

I.e.  will the below be sufficent to ensure that a and b always refer to the same Id.

```rust

thread::spawn(move || {
    for i in 0..10 {
        topo::root!(
            topo::call!( let a = topo::current() );
            topo::call!( let b = topo::current() );
        )
    }
});
```

**Comment by anp** [comment]
Having iterated a bunch more since this was asked, I'm feeling pretty confident that `topo::Id` should be in a thread-local namespace (i.e. you get different roots in different threads). It fits most closely with illicit's constraints (which are themselves motivated by typical UI patterns).

I've documented `illicit`'s thread-local nature more precisely, and I'll add docs to `topo` about this in my coming pass.

**Comment by rebo** [comment]
I agree it should be thread local. I imagine that also means no guarantee of uniqueness, I.e. ids will almost certainly be different over 2 different threads but collisions not impossible? If there was a way to guarantee uniqueness that might hold some value?

**Comment by anp** [comment]
I *think* that with the `Token`-based `Id`s it shouldn't be possible to have collisions at all if the roots differ.

**Comment by anp** [comment]
Hm, actually with adding the `root` API back, if you called exactly the same chain of functions with the same slots on two different threads, you'd get the same `Id` I think. Not so much a collision as a reproduction -- which is kind of the point when you think about it. An `Id` needs to be stable across multiple calls and it shouldn't really matter whether "thread A" does that or "thread B".

**Comment by rebo** [comment]
Yep that makes sense. This means worker threads can process the same execution and get the same result.
