### ISSUE TITLE
moxie.ru Book is Broken

### ISSUE THREAD

**Issue by sdyalor** [anp/moxie#73]
![image](https://user-images.githubusercontent.com/50224521/69213629-a56ee500-0b32-11ea-848b-31a3ea0bf104.png)

Fix please

**Comment by anp** [comment]
Thanks for catching this! Unfortunately still not much there to see at the moment, but I think I've resolved the issue that happened when switching from github pages to netlify. Try clearing your browser cache and post back here if it is still broken?
