### ISSUE TITLE
ICE when Key not accessed

### ISSUE THREAD

**Issue by theduke** [anp/moxie#78]
I stumbled on the following peculiar situation:

When not accessing a key injected via `illicit::from-env`,  building results in a ICE.
The ICE goes away when any access to the key occurs.

moxie: master
nightly: 2019-11-16

```rust
#[topo::nested]
#[illicit::from_env(state: &Key<State>)]
pub fn whatever() {
    // UNcommenting this line removes the ICE
    // let _ = state.field;
    mox!( <p> "Loading..." </p> );
}
```

```
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: DistinctSources(DistinctSources { begin: (Real("src/lib.rs"), BytePos(0)), end: (Real("src/views/some_view.rs"), BytePos(1831)) })', src/libcore/result.rs:1187:5
stack backtrace:
```

**Comment by anp** [comment]
Ha! I saw this happen when I was doing some rebasing and assumed it was because of a stale build directory. By the time I had things reassembled it wasn’t being triggered anymore. Thanks for reporting!

I’ll work on a minimal repro and report upstream.

**Comment by anp** [comment]
All good things come to those who wait, apparently. This compiles OK for me with nightly-2020-01-18:

```rust
#![feature(track_caller)]

use moxie_dom::{elements::p, prelude::*};

#[topo::nested]
#[illicit::from_env(state: &Key<String>)]
pub fn whatever() {
    moxie::mox!( <p> "Loading..." </p> );
}
```

I also suspect that removing the macro invocation for every nested function may have changed this too. Let me know if you run into this again and we'll reopen and dig into it!
